import { LocationConfig, LocationId } from '../types';

export const LOCATIONS: Record<LocationId, LocationConfig> = {
  metropolitan: {
    id: 'metropolitan',
    name: 'Metropolitan City',
    subLocation: 'Central District • 6 km × 6 km',
    initialTime: '07:49',
    timeLabel: 'Morning Rush',
    description: 'Thriving modern metropolis featuring lakes, luxury apartments, mega shopping malls, elevated metro transit, industrial zones, and bustling boulevards.',
    spawnPosition: [0, 15, 30],
    bounds: {
      minX: -120,
      maxX: 120,
      minY: 0.2,
      maxY: 80,
      minZ: -120,
      maxZ: 120,
    },
    camera: {
      position: [110, 85, 110],
      target: [0, 4, 25],
      fov: 36,
    },
    landmarks: [
      { name: 'Shopping Mall', minX: -24, maxX: 6, minZ: -15, maxZ: 15, minY: 0, maxY: 25 },
      { name: 'Metro Station & Viaduct', minX: -30, maxX: -6, minZ: 15, maxZ: 38, minY: 0, maxY: 18 },
      { name: 'Luxury Apartments Cluster', minX: -5, maxX: 35, minZ: -35, maxZ: -5, minY: 0, maxY: 45 },
      { name: 'Lake & Waterfront Park', minX: 25, maxX: 75, minZ: 0, maxZ: 50, minY: 0, maxY: 15 },
      { name: 'Commercial Offices', minX: -50, maxX: -25, minZ: -25, maxZ: 5, minY: 0, maxY: 35 },
      { name: 'Shops & Restaurants', minX: 5, maxX: 35, minZ: 10, maxZ: 35, minY: 0, maxY: 15 },
      { name: 'Hospital Complex', minX: 20, maxX: 50, minZ: 55, maxZ: 85, minY: 0, maxY: 20 },
      { name: 'Industrial Warehouse Zone', minX: -65, maxX: -25, minZ: 35, maxZ: 75, minY: 0, maxY: 15 },
      { name: 'Residential Suburb', minX: 25, maxX: 60, minZ: 35, maxZ: 60, minY: 0, maxY: 12 },
      { name: 'Vishal\'s PG Bedroom Building', minX: 12, maxX: 20, minZ: 23, maxZ: 31, minY: 0, maxY: 12 },
      { name: 'PG Mess & Canteen Building', minX: 22, maxX: 30, minZ: 23, maxZ: 31, minY: 0, maxY: 12 },
      { name: 'PowerFit Fitness Gym', minX: 15, maxX: 25, minZ: 38, maxZ: 46, minY: 0, maxY: 12 },
      { name: 'Under-Bridge Sports & Flower Park', minX: -24, maxX: -12, minZ: 24, maxZ: 90, minY: 0, maxY: 8 },
      { name: 'Sairam College Campus Quad', minX: -42, maxX: -14, minZ: 82, maxZ: 108, minY: 0, maxY: 18 },
      { name: 'Metro Bus Stop & Roadside Shops', minX: 8, maxX: 14, minZ: -14, maxZ: 2, minY: 0, maxY: 6 },
    ],
    waypoints: {
      center: [0, 8, 25],
      mall: [-10, 4, 2],
      metro: [-18, 5, 28],
      lake: [45, 1, 25],
      apartments: [15, 6, -20],
      gym: [20, 2, 42],
      hospital: [35, 4, 68],
      bus_stop: [9.5, 2, -3],
      college: [-28, 2, 95],
      canteen: [26, 2, 27],
      bedroom: [16, 2, 27],
      under_bridge_park: [-18, 2, 50],
    },
  },
  bedroom: {
    id: 'bedroom',
    name: "Vishal's PG Bedroom",
    subLocation: 'Room 204 • South Wing',
    initialTime: '06:00',
    timeLabel: 'Morning Twilight',
    description: "Vishal's personal sanctuary with study desk, bed, and balcony.",
    spawnPosition: [0, 1.8, 0],
    bounds: {
      minX: -3.6,
      maxX: 3.6,
      minY: 0.35,
      maxY: 4.2,
      minZ: -3.8,
      maxZ: 3.6,
    },
    camera: {
      position: [7.2, 6.2, 7.2],
      target: [0, 1.2, 0],
      fov: 38,
    },
    landmarks: [
      {
        name: 'Near Study Desk & Laptop',
        minX: 1.0,
        maxX: 3.4,
        minZ: -3.6,
        maxZ: -1.6,
        minY: 0.5,
        maxY: 2.2,
      },
      {
        name: 'Hovering over Bed & Orange Blanket',
        minX: -3.6,
        maxX: -0.8,
        minZ: -3.6,
        maxZ: -0.6,
        minY: 0.5,
        maxY: 2.2,
      },
      {
        name: 'Near Window & Balcony Door',
        minX: 0.5,
        maxX: 3.6,
        minZ: -4.2,
        maxZ: -3.2,
        minY: 0.5,
        maxY: 3.5,
      },
      {
        name: 'Inspecting Indoor Houseplant',
        minX: 2.5,
        maxX: 3.8,
        minZ: -1.8,
        maxZ: 0.2,
        minY: 0.5,
        maxY: 2.5,
      },
      {
        name: 'Near PG Wardrobe',
        minX: -3.8,
        maxX: -2.4,
        minZ: -3.8,
        maxZ: -1.6,
        minY: 0.5,
        maxY: 3.5,
      },
      {
        name: 'Near Bedroom Entrance',
        minX: -3.8,
        maxX: -2.2,
        minZ: 0.2,
        maxZ: 2.4,
        minY: 0.5,
        maxY: 3.5,
      },
    ],
    waypoints: {
      bed: [-2.2, 0.9, -2.1],
      desk: [2.2, 1.1, -2.6],
      wardrobe: [-3.1, 1.5, -2.7],
      balcony_door: [2.0, 1.4, -3.7],
      center: [0, 1.8, 0],
      entrance: [-3.0, 1.2, 1.3],
    },
  },

  classroom: {
    id: 'classroom',
    name: 'College Lecture Hall',
    subLocation: 'Room CS-301 • Sairam Campus',
    initialTime: '09:30',
    timeLabel: 'Lecture Hours',
    description: 'Tiered academic classroom with student desks, teaching stage, and projector screen.',
    spawnPosition: [-3.4, 1.8, 3.2],
    bounds: {
      minX: -4.5,
      maxX: 4.5,
      minY: 0.35,
      maxY: 4.6,
      minZ: -4.2,
      maxZ: 4.2,
    },
    camera: {
      position: [8.6, 7.2, 8.6],
      target: [0, 1.4, 0],
      fov: 40,
    },
    landmarks: [
      {
        name: 'Teaching Stage & Lecturer Podium',
        minX: -3.0,
        maxX: 3.0,
        minZ: -4.2,
        maxZ: -2.4,
        minY: 0.4,
        maxY: 2.6,
      },
      {
        name: 'Near Giant Presentation Screen',
        minX: -2.2,
        maxX: 2.2,
        minZ: -4.4,
        maxZ: -3.2,
        minY: 1.8,
        maxY: 4.2,
      },
      {
        name: 'Front Row Student Desks',
        minX: -4.0,
        maxX: 4.0,
        minZ: -2.2,
        maxZ: -0.8,
        minY: 0.4,
        maxY: 2.2,
      },
      {
        name: 'Middle Row Student Desks',
        minX: -4.0,
        maxX: 4.0,
        minZ: -0.6,
        maxZ: 0.8,
        minY: 0.4,
        maxY: 2.2,
      },
      {
        name: 'Back Seating & Student Backpacks',
        minX: -4.0,
        maxX: 4.0,
        minZ: 1.0,
        maxZ: 2.4,
        minY: 0.4,
        maxY: 2.2,
      },
      {
        name: 'Center Walking Aisle',
        minX: -0.7,
        maxX: 0.7,
        minZ: -2.0,
        maxZ: 3.2,
        minY: 0.4,
        maxY: 3.0,
      },
      {
        name: 'Classroom Entrance Doorway',
        minX: -4.6,
        maxX: -2.8,
        minZ: 2.4,
        maxZ: 4.2,
        minY: 0.4,
        maxY: 3.2,
      },
    ],
    waypoints: {
      entrance: [-3.4, 1.2, 3.2],
      podium: [0, 1.2, -3.3],
      screen: [0, 2.5, -3.8],
      student_desk_front: [-1.2, 1.1, -1.5],
      student_desk_mid: [1.2, 1.1, 0.0],
      laptop_spot: [-1.2, 1.1, -1.5],
    },
  },

  dining: {
    id: 'dining',
    name: 'PG Dining Area',
    subLocation: 'Ground Floor • Shared Mess',
    initialTime: '13:15',
    timeLabel: 'Lunch Break',
    description: 'Shared student dining space with long mess tables, food serving buffet, and water station.',
    spawnPosition: [-3.2, 1.8, 3.0],
    bounds: {
      minX: -4.2,
      maxX: 4.2,
      minY: 0.35,
      maxY: 4.4,
      minZ: -4.2,
      maxZ: 4.2,
    },
    camera: {
      position: [8.2, 6.8, 8.2],
      target: [0, 1.3, 0],
      fov: 39,
    },
    landmarks: [
      {
        name: 'Buffet Hot Food Counter & Chafing Dishes',
        minX: -3.8,
        maxX: 1.2,
        minZ: -4.2,
        maxZ: -2.5,
        minY: 0.5,
        maxY: 2.5,
      },
      {
        name: 'Kitchen Prep Station & Refrigerator',
        minX: 1.4,
        maxX: 4.0,
        minZ: -4.2,
        maxZ: -2.2,
        minY: 0.5,
        maxY: 3.2,
      },
      {
        name: 'Communal Dining Table',
        minX: -2.4,
        maxX: 2.4,
        minZ: -1.2,
        maxZ: 1.2,
        minY: 0.5,
        maxY: 2.2,
      },
      {
        name: 'Drinking Water Station',
        minX: 2.6,
        maxX: 4.0,
        minZ: 0.8,
        maxZ: 2.4,
        minY: 0.5,
        maxY: 2.5,
      },
      {
        name: 'Mess Notice Board & Meal Menu',
        minX: 3.8,
        maxX: 4.2,
        minZ: -1.5,
        maxZ: 0.5,
        minY: 1.5,
        maxY: 3.0,
      },
      {
        name: 'Dining Hall Entrance Door',
        minX: -4.2,
        maxX: -2.6,
        minZ: 2.2,
        maxZ: 4.0,
        minY: 0.5,
        maxY: 3.0,
      },
    ],
    waypoints: {
      entrance: [-3.2, 1.2, 3.0],
      buffet_counter: [-1.3, 1.2, -3.3],
      dining_table_seat: [0, 1.1, 0],
      water_station: [3.3, 1.2, 1.6],
    },
  },

  gym: {
    id: 'gym',
    name: 'Fitness Gym & Workout Area',
    subLocation: 'Ground Floor • Wellness Wing',
    initialTime: '17:00',
    timeLabel: 'Workout Session',
    description: 'Strength conditioning space equipped with dumbbells, benches, and floor mats.',
    spawnPosition: [0, 1.8, 0],
    bounds: {
      minX: -4.0,
      maxX: 4.0,
      minY: 0.35,
      maxY: 4.2,
      minZ: -4.0,
      maxZ: 4.0,
    },
    camera: {
      position: [7.8, 6.4, 7.8],
      target: [0, 1.2, 0],
      fov: 38,
    },
    landmarks: [
      {
        name: 'Gym Floor & Dumbbells',
        minX: -3.5,
        maxX: 3.5,
        minZ: -3.5,
        maxZ: -1.5,
        minY: 0.4,
        maxY: 2.2,
      },
      {
        name: 'Bench Press Station',
        minX: -2.5,
        maxX: 2.5,
        minZ: -1.0,
        maxZ: 1.5,
        minY: 0.4,
        maxY: 2.0,
      },
      {
        name: 'Treadmill & Cardio Zone',
        minX: 1.5,
        maxX: 3.8,
        minZ: 1.5,
        maxZ: 3.8,
        minY: 0.4,
        maxY: 2.5,
      },
    ],
    waypoints: {
      entrance: [0, 1.2, 3.2],
      warmup_zone: [0, 1.2, 1.5],
      bench_press: [-1.5, 0.9, -0.5],
      dumbbells: [2.2, 1.1, -2.5],
      squat_rack: [-2.2, 1.4, -2.5],
      leg_press: [2.0, 1.1, 0.5],
      cable_machine: [0, 1.5, -3.2],
      rest_bench: [0, 0.9, 0],
    },
  },

  grounds: {
    id: 'grounds',
    name: 'Apartment Grounds & Courtyard',
    subLocation: 'Residential Quad • Outdoor Grounds',
    initialTime: '19:15',
    timeLabel: 'Evening Walk & Call',
    description: 'Open green courtyard and perimeter walkway between buildings.',
    spawnPosition: [0, 1.8, 0],
    bounds: {
      minX: -5.0,
      maxX: 5.0,
      minY: 0.35,
      maxY: 4.8,
      minZ: -5.0,
      maxZ: 5.0,
    },
    camera: {
      position: [8.6, 7.0, 8.6],
      target: [0, 1.2, 0],
      fov: 40,
    },
    landmarks: [
      {
        name: 'Apartment Courtyard Garden',
        minX: -3.0,
        maxX: 3.0,
        minZ: -3.0,
        maxZ: 0.0,
        minY: 0.4,
        maxY: 3.0,
      },
      {
        name: 'Paved Walking Perimeter',
        minX: -4.5,
        maxX: 4.5,
        minZ: 0.5,
        maxZ: 4.5,
        minY: 0.4,
        maxY: 3.0,
      },
    ],
    waypoints: {
      building_exit: [-3.2, 1.2, 3.2],
      path_node_1: [-3.0, 0.8, -2.5],
      path_node_2: [2.5, 0.8, -2.5],
      path_node_3: [2.5, 0.8, 2.5],
      path_node_4: [-3.0, 0.8, 2.5],
      apartment_gate: [0, 1.2, 4.2],
    },
  },

  balcony: {
    id: 'balcony',
    name: "Room 204 Balcony",
    subLocation: 'PG Room • Outdoor Terrace',
    initialTime: '11:00',
    timeLabel: 'Sunlit Balcony',
    description: 'Breezy sunlit balcony with clothesline and view of the neighborhood.',
    spawnPosition: [0, 1.8, 0],
    bounds: {
      minX: -3.2,
      maxX: 3.2,
      minY: 0.35,
      maxY: 3.8,
      minZ: -3.2,
      maxZ: 3.2,
    },
    camera: {
      position: [6.4, 5.2, 6.4],
      target: [0, 1.2, 0],
      fov: 36,
    },
    landmarks: [
      {
        name: 'Balcony Sunlight Railing',
        minX: -2.8,
        maxX: 2.8,
        minZ: -3.0,
        maxZ: -1.0,
        minY: 0.4,
        maxY: 2.2,
      },
      {
        name: 'Clothes Drying Rack',
        minX: -2.0,
        maxX: 2.0,
        minZ: 0.0,
        maxZ: 2.5,
        minY: 0.4,
        maxY: 2.5,
      },
    ],
    waypoints: {
      doorway: [0, 1.2, 2.5],
      clothesline: [0, 1.6, 0.5],
      railing_sunlight: [0, 1.3, -2.0],
      drying_rack: [-1.2, 1.2, 0.5],
    },
  },

  travel: {
    id: 'travel',
    name: 'Transit Corridor',
    subLocation: 'Commute • Road & Campus Gates',
    initialTime: '07:15',
    timeLabel: 'In Transit',
    description: 'Active travel commute between PG accommodation and campus.',
    spawnPosition: [0, 1.8, 0],
    bounds: {
      minX: -4.0,
      maxX: 4.0,
      minY: 0.35,
      maxY: 4.2,
      minZ: -4.0,
      maxZ: 4.0,
    },
    camera: {
      position: [7.2, 6.0, 7.2],
      target: [0, 1.2, 0],
      fov: 38,
    },
    landmarks: [
      {
        name: 'Transit Corridor',
        minX: -3.5,
        maxX: 3.5,
        minZ: -3.5,
        maxZ: 3.5,
        minY: 0.4,
        maxY: 3.0,
      },
    ],
    waypoints: {
      transit: [0, 1.8, 0],
    },
  },
};

/**
 * World coordinate offsets for placing individual interior routine sectors
 * into the Unified Metropolitan Open-World continuous space:
 * - Bedroom: Nested in Greenwood Residency & PG Complex at [20, 0, -8]
 * - Balcony: Attached behind Bedroom at [21.9, 0, -14.2]
 * - Dining: In adjacent Canteen Wing at [34, 0, -8]
 * - Grounds: Complex walking courtyard plaza at [27, 0, 1]
 * - Gym: PowerFit Mega Gym at [26, 0, 10]
 * - Classroom: Sairam College Campus Quad at [-28, 0, 95]
 */
export const LOCATION_WORLD_OFFSETS: Record<LocationId, [number, number, number]> = {
  metropolitan: [0, 0, 0],
  bedroom: [16, 0, 27],
  balcony: [17.9, 0, 20.8],
  dining: [26, 0, 27],
  grounds: [21, 0, 34.5],
  gym: [20, 0, 42],
  classroom: [-28, 0, 95],
  travel: [0, 0, 25],
};

